import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  SolanaWalletConnectors,
} from "../lib/dynamic";

import { GlobalWalletExtension } from "@dynamic-labs/global-wallet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const dynamicEnvId = process.env.NEXT_PUBLIC_DYNAMIC_ENV_ID;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (!dynamicEnvId) {
    const errMsg =
      "Please add your Dynamic Environment to this project's .env file";
    console.error(errMsg);
    throw new Error(errMsg);
  }
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script
          async
          src="https://telegram.org/js/telegram-widget.js?22"
          data-telegram-login="DynamicSafeBot"
          data-size="large"
          data-userpic="false"
          data-auth-url="https://c1813bfcc3ff.ngrok.app/api/v0/sdk/38db2e57-7fb8-4ebe-938b-f6556d58f3c8/telegram/signin"
          data-request-access="write"
        ></script>
      </head>
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: dynamicEnvId,
            walletConnectors: [
              EthereumWalletConnectors,
              SolanaWalletConnectors,
            ],
            walletConnectorExtensions: [GlobalWalletExtension],
          }}
        >
          {children}
        </DynamicContextProvider>
      </body>
    </html>
  );
}
